heat_template_version: 2013-05-23

description: >
  HOT template to create a stack that instantiates the currently selected scenario

parameters:
  pubnet:
    type: string
    description: Name of the public network for this cloud
  mirror_address:
    type: string
    description: Name of the public network for this cloud
  floating_pool:
    type: string
    default: PublicNet
    description: Name of the floating ip pool for this cloud
  image:
    type: string
    default: centos7-64
    description: The image to use for all nodes
  key_name:
    type: string
    default: test2
    description: The key name to use for all nodes
  small_flavor:
    type: string
    default: m1.small
    description: The flavor name to use for small roles
  medium_flavor:
    type: string
    default: m1.medium
    description: The flavor name to use for medium roles
  config_repo:
    type: string
    default: 'https://github.com/michaeltchapman/puppet_openstack_builder'
    description: Git repo that contains the configuration for this test run
  config_ref:
    type: string
    default: master
    description: Git ref to checkout

resources:
  mgmt_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: pubnet }

  mgmt_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      subnet_id: { get_resource: mgmt_subnet }
      router_id: { get_resource: mgmt_router }

  mgmt_network:
    type: OS::Neutron::Net

  mgmt_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: mgmt_network }
      cidr: 192.168.242.0/24
      dns_nameservers:
        - 8.8.8.8

  control1_floatingip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: floating_pool }

  control1_floatingip_ass:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: control1_floatingip }
      server_id: { get_resource: control1 }
    depends_on:
      - mgmt_router_interface
      - mgmt_router

  infra1_mgmt:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: mgmt_network }
      fixed_ips:
        - subnet_id: { get_resource: mgmt_subnet  }
      security_groups:
        - { get_resource: test_secgroup }

  control1_mgmt:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: mgmt_network }
      fixed_ips:
        - subnet_id: { get_resource: mgmt_subnet  }
      security_groups:
        - { get_resource: test_secgroup }

  hyper1_mgmt:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: mgmt_network }
      fixed_ips:
        - subnet_id: { get_resource: mgmt_subnet  }
      security_groups:
        - { get_resource: test_secgroup }

  internal_net:
    type: OS::Neutron::Net

  control1_int:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: internal_net  }
      fixed_ips:
        - subnet_id: { get_resource: internal_subnet  }
      security_groups:
        - { get_resource: test_secgroup }

  hyper1_int:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: internal_net  }
      fixed_ips:
        - subnet_id: { get_resource: internal_subnet  }
      security_groups:
        - { get_resource: test_secgroup }

  internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: internal_net }
      cidr: 10.3.3.0/24
      gateway_ip: null
      dns_nameservers:
        - 8.8.8.8

  external_net:
    type: OS::Neutron::Net

  external_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: external_net }
      cidr: 10.2.3.0/24
      gateway_ip: null
      dns_nameservers:
        - 8.8.8.8

  hyper1_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: external_net  }
      fixed_ips:
        - subnet_id: { get_resource: external_subnet  }
      security_groups:
        - { get_resource: test_secgroup }

  control1_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: external_net  }
      fixed_ips:
        - subnet_id: { get_resource: external_subnet  }
      security_groups:
        - { get_resource: test_secgroup }

  test_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security group for test build server allowing http and ssh
      rules:
        - direction: ingress
          protocol: udp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0

  infra1:
    type: OS::Nova::Server
    properties:
      name: infra1 
      image: { get_param: image}
      flavor: { get_param: small_flavor}
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: infra1_mgmt }
      metadata:
        mgmt_iface: eth0
        mgmt_address: '%{ipaddress_eth0}'
        public_iface: eth0
        public_address: '%{ipaddress_eth0}'
        internal_iface: eth0
        internal_address: '%{ipaddress_eth0}'
        build_mgmt: { get_param: mirror_address }
      user_data:
        str_replace:
          template: |
            #!/usr/bin/env bash
            ethtool -K eth0 tso off
            ethtool -K eth0 gso off
            ethtool -K eth0 gro off
            yum install -y git
            git clone __config_repo /vagrant
            cd /vagrant
            git checkout __config_ref
            bash -x provision/bootstrap.sh &> /root/bootstrap.log
          params:
            __config_repo: { get_param: config_repo }
            __config_ref: { get_param: config_ref }

  infra2:
    type: OS::Nova::Server
    properties:
      name: infra2
      image: { get_param: image}
      flavor: { get_param: small_flavor}
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: mgmt_network }
      security_groups:
        - { get_resource: test_secgroup }
      metadata:
        mgmt_iface: eth0
        mgmt_address: '%{ipaddress_eth0}'
        public_iface: eth0
        public_address: '%{ipaddress_eth0}'
        internal_iface: eth0
        internal_address: '%{ipaddress_eth0}'
        build_mgmt: { get_param: mirror_address }
        infra1_mgmt: { get_attr: [ infra1_mgmt, fixed_ips, 0, ip_address ]}
      user_data:
        str_replace:
          template: |
            #!/usr/bin/env bash
            ethtool -K eth0 tso off
            ethtool -K eth0 gso off
            ethtool -K eth0 gro off
            yum install -y git
            git clone __config_repo /vagrant
            cd /vagrant
            git checkout __config_ref
            bash -x provision/bootstrap.sh &> /root/bootstrap.log
          params:
            __config_repo: { get_param: config_repo }
            __config_ref: { get_param: config_ref }

  infra3:
    type: OS::Nova::Server
    properties:
      name: infra3
      image: { get_param: image}
      flavor: { get_param: small_flavor}
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: mgmt_network }
      security_groups:
        - { get_resource: test_secgroup }
      metadata:
        mgmt_iface: eth0
        mgmt_address: '%{ipaddress_eth0}'
        public_iface: eth0
        public_address: '%{ipaddress_eth0}'
        internal_iface: eth0
        internal_address: '%{ipaddress_eth0}'
        build_mgmt: { get_param: mirror_address }
        infra1_mgmt: { get_attr: [ infra1_mgmt, fixed_ips, 0, ip_address ]}
      user_data:
        str_replace:
          template: |
            #!/usr/bin/env bash
            ethtool -K eth0 tso off
            ethtool -K eth0 gso off
            ethtool -K eth0 gro off
            yum install -y git
            git clone __config_repo /vagrant
            cd /vagrant
            git checkout __config_ref
            bash -x provision/bootstrap.sh &> /root/bootstrap.log
          params:
            __config_repo: { get_param: config_repo }
            __config_ref: { get_param: config_ref }

  control1:
    type: OS::Nova::Server
    properties:
      name: control1
      image: { get_param: image}
      flavor: { get_param: medium_flavor}
      key_name: { get_param: key_name}
      networks:
        - port: { get_resource: control1_mgmt}
        - port: { get_resource: control1_ext}
        - port: { get_resource: control1_int}

      user_data:
        str_replace:
          template: |
            #!/usr/bin/env bash
            ethtool -K eth0 tso off
            ethtool -K eth0 gso off
            ethtool -K eth0 gro off
            yum install -y git
            git clone __config_repo /vagrant
            cd /vagrant
            git checkout __config_ref
            bash -x provision/bootstrap.sh &> /root/bootstrap.log
          params:
            __config_repo: { get_param: config_repo }
            __config_ref: { get_param: config_ref }

      metadata:
        mgmt_iface: eth0
        mgmt_address: "%{ipaddress_eth0}"
        public_iface: eth1
        public_address: "%{ipaddress_eth1}"
        internal_iface: eth2
        internal_address: "%{ipaddress_eth2}"
        control_public: { get_attr: [ control1_ext, fixed_ips, 0, ip_address ]}
        control_internal: { get_attr: [ control1_int, fixed_ips, 0, ip_address ]}
        infra1_mgmt: { get_attr: [ infra1_mgmt, fixed_ips, 0, ip_address ]}
        build_mgmt: { get_param: mirror_address }

  hyper1:
    type: OS::Nova::Server
    properties:
      name: hyper1
      image: { get_param: image}
      flavor: { get_param: medium_flavor}
      key_name: { get_param: key_name}
      networks:
        - port: { get_resource: hyper1_mgmt}
        - port: { get_resource: hyper1_ext}
        - port: { get_resource: hyper1_int}

      user_data:
        str_replace:
          template: |
            #!/usr/bin/env bash
            ethtool -K eth0 tso off
            ethtool -K eth0 gso off
            ethtool -K eth0 gro off
            yum install -y git
            git clone __config_repo /vagrant
            cd /vagrant
            git checkout __config_ref
            bash -x provision/bootstrap.sh &> /root/bootstrap.log
          params:
            __config_repo: { get_param: config_repo }
            __config_ref: { get_param: config_ref }

      metadata:
        control_public: { get_attr: [ control1_ext, fixed_ips, 0, ip_address ]}
        control_internal: { get_attr: [ control1_int, fixed_ips, 0, ip_address ]}
        mgmt_iface: eth0
        mgmt_address: "%{ipaddress_eth0}"
        public_iface: eth1
        public_address: "%{ipaddress_eth1}"
        internal_iface: eth2
        internal_address: "%{ipaddress_eth2}"
        infra1_mgmt: { get_attr: [ infra1_mgmt, fixed_ips, 0, ip_address ]}
        build_mgmt: { get_param: mirror_address }
